### ISSUE TITLE
Language names are in English

### ISSUE THREAD

**Issue by gunchleoc** [acmepjz/meandmyshadow#24]
When users select their language, the language names are displayed in English. It would be nice to use native names.

One possible way to solve this is to have an extra configuration file.

Reliable native languages names can be sourced from https://unicode.org/cldr/charts/latest/summary/root.html

**Comment by acmepjz** [comment]
The language name is contained in tinygettext source code, `language.cpp`. Maybe we should ask them if the localized language names should be added. I also checked SuperTuxKart which displays localized language names.

But there are one extra problem which need to be resolved: currently the font files depend on the language we are choosing. This will cause problems e.g. when choosing Simplified Chinese if the current language is English you will see boxes instead of Chinese characters. My idea is to implement a simple font fallback support in SDL2_ttf, in fact I'm working on this on a separate branch (not yet pushed onto Github 😅).

**Comment by gunchleoc** [comment]
You're right, the font support needs to be solved first. It is a good idea to have mixed font anyway, for incomplete translations. I found that some of the nicer-looking fonts available for non-Latin scripts have crap Latin characters or none at all.

**Comment by acmepjz** [comment]
I have implemented font fallback in a separate branch <https://github.com/acmepjz/meandmyshadow/tree/sdl2-ttf-font-fallback> and the localized language name feature is also implemented. I will merge this branch into master after V0.5 version released.

Do you think it's OK to include this change into V0.5? I think it is a major change which needs some more tests. It also changes the dependency as well (previous: SDL2_ttf, new: freetype).

**Comment by acmepjz** [comment]
already fixed in V0.5.1 Development version
